### ISSUE TITLE
Cross Compile Issues

### ISSUE THREAD

**Issue by michaeladler** [siemens/mtda#107]
I have noticed that this layer fails to build using `ISAR_CROSS_COMPILE = "1"` (which is often enabled globally in downstream layers which may depend on this layer). It seems that mostly Python packages are affected by this, e.g.

* curve25519-donna
* hap-python

(this list is most likely incomplete)

It would be nice if this layer could be built when cross-compilation is enabled globally. There are two viable approaches:

1. Fix the problematic recipes (e.g. by depending on python-whatever:**native**).
2. Disable cross-compilation for recipes which cannot be fixed easily.

**Comment by chombourger** [comment]
will check. thanks for reporting this issue.

**Comment by chombourger** [comment]
`ed25519` is also impacted

**Comment by chombourger** [comment]
@michaeladler here's https://github.com/siemens/mtda/pull/108
going to burn the nanopi image to make sure it is all ok

**Comment by michaeladler** [comment]
That's great, thanks! Looking forward to it.
