### ISSUE TITLE
support xz compressed images

### ISSUE THREAD

**Issue by chombourger** [siemens/mtda#121]
use https://github.com/Rogdham/python-xz to support .xz images

**Comment by vj-kumar** [comment]
Not sure if someone is looking into to it. Planing to take it.

**Comment by chombourger** [comment]
> Not sure if someone is looking into to it. If not planing to take it.

Thanks!

**Comment by vj-kumar** [comment]
@chombourger Any specific reason for using python-xz? Looks like lzma can do it to. I do see some benefits mentioned in python-xz, but currently not sure whether it will have an impact.

**Comment by jan-kiszka** [comment]
If you are talking about isar image compression: Adriaan has started porting over the OE image compression features. That will obsolete the currently needed custom image classes.

**Comment by vj-kumar** [comment]
@jan-kiszka This is about mtda's storage writer supporting xz compressed images. https://github.com/siemens/mtda/blob/a13e98c44271218adfb850f23119a9788234265b/mtda/storage/writer.py#L49-L60

**Comment by vj-kumar** [comment]
Bz2 write is broken. Tested in Qemu, Richa also validated in an actual board. XZ similar implementation to BZ2 also doesnot work. Checking.

**Comment by chombourger** [comment]
Thanks for the info. We will get a framework to test our APIs and features With https://github.com/siemens/mtda/pull/146 and hopefully avoid regressions in the future

**Comment by vj-kumar** [comment]
Related to https://github.com/siemens/mtda/issues/147

Planning to address #147 before getting here.
