### ISSUE TITLE
Hardware support for BeagleBone Black

### ISSUE THREAD

**Issue by chombourger** [siemens/mtda#128]

**Comment by vj-kumar** [comment]
I also seem to have a BBB rev c :)

**Comment by chombourger** [comment]
I created this issue because Hemanth is still using his bbb to run mtda but probably with a Debian 10 base. Since we do not require a lot, we may be able to build a Debian 11 image that uses both mainline u-boot and kernel

**Comment by hkoturap** [comment]
Presently we were using https://github.com/MentorEmbedded/industrial-mtda/blob/mel/master/mtda-bbb-for-ipc.yml to build bbb images.Was facing following issue when trying to build                                                       

hemanth@hemanth:/home/hemanth/industrial-mtda/build$ ../industrial-core/scripts/mel-create-stick

# checking build settings...

ERROR: ParseError at /home/hemanth/industrial-mtda/isar/meta/classes/image.bbclass:178: Could not inherit file classes/${PRODUCTION_IMAGE_TYPE}.bbclass

warning: '' is not a supported compression format. Using bzip2 instead
