### ISSUE TITLE
mtda_apt_uri: apt update error "Bad Gateway"

### ISSUE THREAD

**Issue by ricbha** [siemens/mtda#134]
Error on running apt-get update:
`W: Failed to fetch https://dl.bintray.com/chombourger/mtda/dists/bullseye/InRelease  502  Bad Gateway [IP: 54.70.2.80 443]
`
As added from https://github.com/siemens/mtda/blob/master/meta-isar/recipes-core/images/mtda-image.inc#L81 :
```
mtda@mtda:~$ cat /etc/apt/sources.list.d/mtda.list
deb [trusted=yes] https://dl.bintray.com/chombourger/mtda bullseye main
```

**Comment by chombourger** [comment]
right, bintray should be removed since the service was sunset sometime last year

**Comment by chombourger** [comment]
looks like we need to update meta-isar/recipes-core/images/mtda-image.inc

**Comment by chombourger** [comment]
would you like to propose a fix @ricbha ?

**Comment by ricbha** [comment]
> chombourger/mtda

Yes ofcourse. Do we have apt available at gemfury or we need to create one?

**Comment by chombourger** [comment]
> > chombourger/mtda
> 
> Yes ofcourse. Do we have apt available at gemfury or we need to create one?

cool. yes we do have feeds up. see https://github.com/siemens/mtda/blob/master/docs/install.rst#using-apt

The entry should now read:
```
deb [trusted=yes] https://apt.fury.io/mtda/ /
```
