### ISSUE TITLE
power/qemu: Provide configuration for multiple cpu cores for the QEMU target

### ISSUE THREAD

**Issue by GuBi34** [siemens/mtda#176]
For demanding DUT's the assignment of multiple CPU cores is wishful to increase the virtual machine's performance.

Here a proposed change for it (after review).

https://github.com/siemens/mtda/pull/175/commits/3495d018b0048193b8c06eaaed0da58025b434a7

**Comment by chombourger** [comment]
good idea and thank you so much for your first contribution!

**Comment by chombourger** [comment]
Fixed with #175
