### ISSUE TITLE
Autostart stumbles over ttyUSB availability

### ISSUE THREAD

**Issue by jan-kiszka** [siemens/mtda#232]
```
Mar 06 08:05:32 mtda systemd[1]: Started Multi-Tenant Device Access.
Mar 06 08:05:38 mtda mtda-cli[364]: Probe of the serial console failed!
Mar 06 08:05:38 mtda mtda-cli[364]: Failed to start the MTDA server!
Mar 06 08:05:38 mtda systemd[1]: mtda.service: Succeeded.
Mar 06 08:05:38 mtda systemd[1]: mtda.service: Consumed 3.853s CPU time.
```
Actually two issue: The serial console is not yet available - are we missing some dependency in the service? Starting manually later on works.

Second issue: The service reports success.

**Comment by jan-kiszka** [comment]
At least the primary bug relates to the pause/resume race (see #225) and is resolved by not executing those functions. Autostart works now.

What remains is error-free termination under error conditions.

**Comment by chombourger** [comment]
How about having a recipe shipping a systemd drop-in to make the systemd service wait for /dev/ttyUSB0 like done for /dev/sda with [meta-isar/recipes-conf/mass-storage/usb-ms-use-sda_0.6.bb](https://github.com/siemens/mtda/blob/master/meta-isar/recipes-conf/mass-storage/usb-ms-use-sda_0.6.bb)

**Comment by jan-kiszka** [comment]
Well, it remains a local configuration decision. I'm using a USB-serial converter right now, but I could imagine connecting the RPi on-board UART directly with the target.
