### ISSUE TITLE
c2g: Unable to read console on development-image

### ISSUE THREAD

**Issue by badrikeshp-mg** [siemens/mtda#241]
Unable to read console on development image

Issue observed after the commit: https://github.com/MentorEmbedded/hmi-edition/pull/63/files

Note: IMAGE_FEATURES_append = " mtda " is added at the end of conf/local.conf in the build directory

**Comment by badrikeshp-mg** [comment]
Note:
- Login prompt appears fine on mtda-console after removing the line: IMAGE_FEATURES_append = " setup ~initial-setup"
OR
- Enabling serial-getty@ttyACM0 in: hmi-edition/recipes-conf/images/configure-development-image.bbappend

**Comment by chombourger** [comment]
Please create an issue in our INDLIN project, not here (this is not an issue with mtda per se but rather how Industrial OS uses mtda)
