### ISSUE TITLE
mtda-systemd-helper output gets destroyed on reboot

### ISSUE THREAD

**Issue by jan-kiszka** [siemens/mtda#265]
I'm running 0.17 release, `kas/debian/mtda-rpi4b.yml`, and a config that has
```
[console]
variant  = serial
port     = /dev/ttyUSB0
rate     = 115200
```
When I run mtda-systemd-helper manually or restart the mtda-config service, I get
```
root@mtda:~# ls -l /lib/systemd/system/mtda.service.d/
total 4
-rw-r--r-- 1 root root 57 Jan  7 10:42 auto-dep-console.conf
```
But right after the next reboot:
```
root@mtda:~# ls -l /lib/systemd/system/mtda.service.d/
total 0
```
Dependencies were still correctly applied on this boot, but they obviously will no longer exists for succeeding ones.

I'm working around this now with a manually generated `/etc/systemd/system/mtda.service.d/dep-console.conf` (BTW, this is the folder where mtda-systemd-helper should write to as well), just wanted to let you now that the magic is broken.

**Comment by chombourger** [comment]
Thanks for letting us know!
