### ISSUE TITLE
mtda.readthedocs.io/en/latest out of date

### ISSUE THREAD

**Issue by bovi** [siemens/mtda#272]
I notice that the website is out of date. 

Example: 

```https://mtda.readthedocs.io/en/latest/config.html```

Doesn't contain for example ```shellcmd``` as in the source:

```https://github.com/siemens/mtda/blob/master/docs/config.rst```

**Comment by chombourger** [comment]
Thanks for reporting. I guess I need to check why the link "latest" isn't being updated
The following appears to work: https://mtda.readthedocs.io/en/stable/config.html#power-settings

**Comment by chombourger** [comment]
This was an issue with the webhook. Changes done in the project settings:

- made `stable` the default version on mtda.readthedocs.io
- trigger the webhook on both pushes and tags (only the latter was previously enabled)

**Comment by chombourger** [comment]
I believe this issue may now be closed
