### ISSUE TITLE
Nanopi relay wiring diagram looks incorrect 

### ISSUE THREAD

**Issue by WiseLord** [siemens/mtda#294]
README.md refers to  neo_block_diagram.png where 5V relay connected to three NanoPi Neo pins.

According to the picture, relay's GND is connected to GPIO PG7, that I find wrong (I would expect it to be connected to some of GND pins).

Documentation at https://mtda.readthedocs.io/en/latest/build.html#id3 is also affected

**Comment by chombourger** [comment]
thank you @WiseLord for reporting and thank you @bhargavdas for the fix!
