### ISSUE TITLE
New storage device support

### ISSUE THREAD

**Issue by furkanozogul** [siemens/mtda#326]
We have Usb-Sd-Mux device from Linux Automation GMbh and this device doesn't support  by mtda.
The device controlled by usbsdmux app which is python based.
You can find the manual on this web page: https://github.com/linux-automation/usbsdmux.

Could you please support this device?

**Comment by chombourger** [comment]
this would be a good addition to the project. Since we do not have such devices at hand you may consider a hardware donation to the project as a mean to contribute to the project

**Comment by chombourger** [comment]
bookworm is now shipping the usbsdmux package: https://packages.debian.org/bookworm/usbsdmux

**Comment by chombourger** [comment]
Done with #402 
Credits to @jan-kiszka
