### ISSUE TITLE
unable to install prebuilt packages on Ubuntu 20.04

### ISSUE THREAD

**Issue by chombourger** [siemens/mtda#97]
Reported by @bhargavdas 

after adding fury.io/mtda to source list and then while installing  mtda getting dependency errors,
mainly for python3-zstandard 

`python3-zstandard : Depends: python3 (>= 3.9~) but 3.8.2-0ubuntu2 is to be installed`

**Comment by bhargavdas** [comment]
This issue is also observed in debian 10 which has `python3.7` installed.

**Comment by chombourger** [comment]
> This issue is also observed in debian 10 which has `python3.7` installed.

right. this will be subject of a separate issue (if we find ourselves wanting to support buster)

**Comment by chombourger** [comment]
#98 should help

**Comment by chombourger** [comment]
0.15 packages at https://launchpad.net/~chombourger/+archive/ubuntu/mtda-focal
They were created with a script that ill be added to our GitHub actions
